# Third Data Preparation Process

In this notebook file, the dataset provided by the customer will be eddited for general purposes.

The Product feature will be examined in depth.

In [1]:
#Library is being imported
import pandas as pd

In [2]:
#Library version is being printed
print('pandas Version: ' + pd.__version__)

pandas Version: 1.5.2

In [3]:
#A pandas dataframe named as dataFrame is being created by reading the data pkl file created last process
dataFrame = pd.read_pickle("../Data/CleanedData/FabricWaste.pkl")
dataFrame.head()

,Product,Color,ProductDetail,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,M6030 JERSEY SHIRT LANGARM,PINIE,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,375,405,20,399,6
1,M6030 JERSEY SHIRT LANGARM,PFIRSICH,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,22,411,3
2,M6030 JERSEY SHIRT LANGARM,HELLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,389,19,378,11
3,M6030 JERSEY SHIRT LANGARM,PETROLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,18,406,8
4,M6030 JERSEY SHIRT LANGARM,AUBERGINE 2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,16,411,3

In [4]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product          186 non-null    object
 1   Color            186 non-null    object
 2   ProductDetail    186 non-null    object
 3   FabricCode       186 non-null    object
 4   FabricDetail     186 non-null    object
 5   IsManualProcess  186 non-null    bool
 6   Weight           186 non-null    int64
 7   Width            186 non-null    int64
 8   ProductPart      186 non-null    int64
 9   NotchLayer       186 non-null    int64
 10  NotchQuantity    186 non-null    int64
 11  OrderQuantity    186 non-null    int64
 12  Quantity         186 non-null    int64
 13  Repair           186 non-null    int64
 14  Delivery         186 non-null    int64
 15  SecondQuality    186 non-null    int64
dtypes: bool(1), int64(10), object(5)
memory usage: 22.1+ KB

In [5]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,165.241935,159.435484,4.801075,44.483871,2.467742,294.489247,317.209677,6.387097,309.295699,7.913978
std,36.999935,15.936653,2.289388,21.042615,0.792896,113.160409,123.932912,4.987622,122.519425,6.432445
min,125.000000,120.000000,2.000000,0.000000,0.000000,100.000000,110.000000,0.000000,110.000000,0.000000
25%,125.000000,150.000000,4.000000,31.000000,2.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,172.500000,160.000000,4.000000,39.000000,3.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,190.000000,171.500000,5.000000,58.000000,3.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,250.000000,180.000000,14.000000,111.000000,4.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [6]:
#Number of unique values of each column are being printed
dataFrame.nunique()

Product             80
Color               34
ProductDetail       21
FabricCode           9
FabricDetail        12
IsManualProcess      2
Weight               6
Width                8
ProductPart         12
NotchLayer          31
NotchQuantity        5
OrderQuantity       37
Quantity           106
Repair              22
Delivery           131
SecondQuality       27
dtype: int64

In [7]:
#Too many unique values for a categorical attribute in Product column
#In order to use this feature effectively, the values in the column should be processed
#Unique Product are being printed
dataFrame['Product'].unique()

array(['M6030 JERSEY SHIRT LANGARM', 'M6031 JERSEY SHIRT KURZARM',
       'M6032 JERSEY TOP', 'M6033 JERSEY SHIRT WICKELOPTIK',
       'M6034 JERSEY HOSE ORIENT',
       'M6035 JERSEY SHIRT KURZARM MIT FRONTPRINT',
       'M6036 JERSEY SHIRT LANGARM MIT KETTELKANTE',
       'M6037 JERSEY SHIRT 1/2 ARM MIT KETTELKANTE',
       'M6038 JERSEY TOP MIT KETTELKANTE', 'M6039 JERSEYBLUSE',
       'M6041 JERSEYJKLEID IN WICKELOPTIK',
       'M6042 NACHTHEMD MIT ÜBERSCHNITTENER SCHULTER',
       'M6043 SCHLAFANZUG LANG HERREN', 'M6044 SCHLAFANZUG KURZ HERREN',
       'M6045 NACHTHEMD MIT HALBARM', 'M6046 PYJAMAHOSE',
       'M6047 PYJAMAHOSE KURZ', 'M6048 PYJAMAHOSE',
       'M6049 JERSEYSHIRT KURZARM', 'M6050 NACHTHEMD KURZARM',
       'M6051 PYJAMAHOSE', 'M6052 JERSEYKLEID WENDERINGEL',
       'M6053 JERSEYSHIRT WENDERINGEL HERREN',
       'M6054 JERSEY SHIRT WENDERINGEL',
       'M6055 JERSEYBLUSE MIT KURZEM ARM', 'M6056 JERSEYROCK',
       'M6058 JERSEYSHIRT V', 'M6059 JERSEY SHIRT KURZARM',
       'M6061 JERSEYHOSE  ', 'M6062 JERSEYSHIRT',
       'M6063 JERSEYKLEID OHNE ARM', 'M6064 JERSEYROCK',
       'M6065 LEGGING LANG', 'M6066 JERSEYHOSE SPORTIV',
       'M6067 JERSEYTUNIKA', 'M6068 JERSEYSHIRT V KURZARM',
       'M6069 JERSEYSHIRT HANF LANGARARM HERREN',
       'M6070 JERSEYSHIRT HANF KURZARM HERREN',
       'M6071 LEINENSHIRT 3 4 ARM', 'M6072 DOPPELLAGIGES LEINENSHIRT',
       'M6073 LEINENSHIRT MIT KURZEM ARM', 'M6074 JERSEYSHIRT RIPPE ',
       'M6075 JERSEYTOP RIPPE', 'M6076 NACHTHEMD RIPPE',
       'M6206 JERSEYKLEID', 'M6220 LEGGING KURZ',
       'M6015 WENDERINGEL KLEID', 'M6017 WENDERİNGEL SWEATER',
       'M6018 WENDERİNGEL HOODİE', 'M6019 WENDERİNGEL BERMUDA',
       'M6020 BABY BASICSHIRT SHORTSLEEVE',
       'M6021 BABY BASICSHIRT LONGSLEEVE',
       'M6022  BASICSHIRT 1 4 ARM GERADE FORM',
       'M6023 BASICSHIRT 1 1 ARM, GERADE FORM', 'M6024  JERSEYHOSE UNI',
       'M6025 JERSEYBERMUDA', 'M6026 HOSENROCK MELANGE',
       'M6027 TUNIKA - KLEID SAUMSTICKEREI', 'M6028 ROCK MIT STICKEREI',
       'M6029 T-SHIRT 1 4 ARM WITH FRONTPRINT', 'M6099 BABY JERSEYHOSE',
       'M6100 BASICSHIRT SHORTSLEEVE', 'M6101 BASICSHIRT LONGSLEEVE',
       'M6102 LEGGING LANG', 'M6103 3/4 LEGGING',
       'M6104 NACHTHEMD AOP BLÜMCHEN', 'M6105 PYJAMA ',
       'M6107 SOMMER SCHLAFANZUG', 'M6108 SCHLAFANZUG LANG',
       'M6109 RIPPSHIRT', 'M6110 KLEID', 'M6141 JERSEYKLEİD BLUMENWİESE',
       'M6142 HAARBAND MİT KNOTEN', 'M6143 JERSEYHOSE AOP',
       'M6144 T-SHİRT AOP', 'M6145 WENDE KAPUZENSHİRT',
       'M6146 ROCK BLUMENWİESE', 'M6151 KURZER SCHLAFANZUG',
       'M6225 BERMUDA UNTER WASSER', 'M6438 JERSEYROCK FLEUR'],
      dtype=object)

In [8]:
#Since the information that can be extracted from Product column can be extracted in more detail from other columns
#Product column is being removed from dataFrame
dataFrame.drop('Product', axis = 1, inplace = True)

In [9]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Color            186 non-null    object
 1   ProductDetail    186 non-null    object
 2   FabricCode       186 non-null    object
 3   FabricDetail     186 non-null    object
 4   IsManualProcess  186 non-null    bool
 5   Weight           186 non-null    int64
 6   Width            186 non-null    int64
 7   ProductPart      186 non-null    int64
 8   NotchLayer       186 non-null    int64
 9   NotchQuantity    186 non-null    int64
 10  OrderQuantity    186 non-null    int64
 11  Quantity         186 non-null    int64
 12  Repair           186 non-null    int64
 13  Delivery         186 non-null    int64
 14  SecondQuality    186 non-null    int64
dtypes: bool(1), int64(10), object(4)
memory usage: 20.7+ KB

In [10]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,165.241935,159.435484,4.801075,44.483871,2.467742,294.489247,317.209677,6.387097,309.295699,7.913978
std,36.999935,15.936653,2.289388,21.042615,0.792896,113.160409,123.932912,4.987622,122.519425,6.432445
min,125.000000,120.000000,2.000000,0.000000,0.000000,100.000000,110.000000,0.000000,110.000000,0.000000
25%,125.000000,150.000000,4.000000,31.000000,2.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,172.500000,160.000000,4.000000,39.000000,3.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,190.000000,171.500000,5.000000,58.000000,3.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,250.000000,180.000000,14.000000,111.000000,4.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [11]:
#dataFrame is being saved as pkl files
dataFrame.to_pickle("../Data/WithRelationalTables/FabricWasteProduct.pkl")