# First Data Preparation Process

In this notebook file, the dataset provided by the customer will be eddited for general purposes.

Features that are meaningless or unusable will be removed from the dataset.

In [1]:
#Library is being imported
import pandas as pd

In [2]:
#Library version is being printed
print('pandas Version: ' + pd.__version__)

pandas Version: 1.5.2

In [3]:
#A pandas dataframe named as dataFrame is being created by reading the data from an excel file
dataFrame = pd.read_excel('../Data/RawData/FabricWaste.xlsx')
dataFrame.head()

,OrderNo,Product,Color,ProductDetail,FabricCode,FabricDetail,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Planned,Quantity,Print,Repair,Delivery,SecondQuality,Reason1,Reason2
0,4982,M6030 JERSEY SHIRT LANGARM,PINIE,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,35,3,375,414,405,405,20,399,6,NaN,NaN
1,4982,M6030 JERSEY SHIRT LANGARM,PFIRSICH,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,22,411,3,NaN,NaN
2,4982,M6030 JERSEY SHIRT LANGARM,HELLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,389,389,19,378,11,NaN,Dikimsel Hatalar.
3,4982,M6030 JERSEY SHIRT LANGARM,PETROLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,18,406,8,NaN,NaN
4,4982,M6030 JERSEY SHIRT LANGARM,AUBERGINE 2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,16,411,3,NaN,NaN

In [4]:
#Information of dataFrame is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderNo        186 non-null    int64
 1   Product        186 non-null    object
 2   Color          186 non-null    object
 3   ProductDetail  186 non-null    object
 4   FabricCode     186 non-null    object
 5   FabricDetail   186 non-null    object
 6   Weight         186 non-null    int64
 7   Width          186 non-null    object
 8   ProductPart    186 non-null    int64
 9   NotchLayer     186 non-null    object
 10  NotchQuantity  178 non-null    object
 11  OrderQuantity  186 non-null    int64
 12  Planned        186 non-null    int64
 13  Quantity       186 non-null    int64
 14  Print          186 non-null    int64
 15  Repair         186 non-null    int64
 16  Delivery       186 non-null    int64
 17  SecondQuality  186 non-null    int64
 18  Reason1        29 non-null     object
 19  Reason2        44 non-null     object
dtypes: int64(10), object(10)
memory usage: 29.2+ KB

In [5]:
#Statistical information of dataFrame is being printed
dataFrame.describe()

,OrderNo,Weight,ProductPart,OrderQuantity,Planned,Quantity,Print,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,4982.365591,165.241935,4.801075,294.489247,325.000000,317.209677,317.209677,6.387097,309.311828,7.897849
std,0.482895,36.999935,2.289388,113.160409,122.968333,123.932912,123.932912,4.987622,122.498051,6.454439
min,4982.000000,125.000000,2.000000,100.000000,110.000000,110.000000,110.000000,0.000000,112.000000,-2.000000
25%,4982.000000,125.000000,4.000000,206.250000,229.000000,224.000000,224.000000,3.000000,217.000000,4.000000
50%,4982.000000,172.500000,4.000000,250.000000,278.000000,272.000000,272.000000,6.000000,265.000000,6.000000
75%,4983.000000,190.000000,5.000000,380.000000,419.000000,414.000000,414.000000,8.000000,407.500000,10.000000
max,4983.000000,250.000000,14.000000,640.000000,695.000000,698.000000,698.000000,30.000000,690.000000,38.000000

In [6]:
#When information of dataFrame is examined, it is seen that there are only 29 non-null values for the Reason 1 column,
#and 44 non-null values for the Reason2 column

#Since these columns take string values and contain a large number of null values,
#it seems very difficult to use them by handling them

#Reason1 and Reason2 columns are being removed
dataFrame.drop('Reason1', axis = 1, inplace = True)
dataFrame.drop('Reason2', axis = 1, inplace = True)
dataFrame.head()

,OrderNo,Product,Color,ProductDetail,FabricCode,FabricDetail,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Planned,Quantity,Print,Repair,Delivery,SecondQuality
0,4982,M6030 JERSEY SHIRT LANGARM,PINIE,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,35,3,375,414,405,405,20,399,6
1,4982,M6030 JERSEY SHIRT LANGARM,PFIRSICH,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,22,411,3
2,4982,M6030 JERSEY SHIRT LANGARM,HELLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,389,389,19,378,11
3,4982,M6030 JERSEY SHIRT LANGARM,PETROLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,18,406,8
4,4982,M6030 JERSEY SHIRT LANGARM,AUBERGINE 2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,16,411,3

In [7]:
#OrderNo is being removed from the dataset as it does not make any sense in this project
dataFrame.drop('OrderNo', axis = 1, inplace = True)
dataFrame.head()

,Product,Color,ProductDetail,FabricCode,FabricDetail,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Planned,Quantity,Print,Repair,Delivery,SecondQuality
0,M6030 JERSEY SHIRT LANGARM,PINIE,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,35,3,375,414,405,405,20,399,6
1,M6030 JERSEY SHIRT LANGARM,PFIRSICH,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,22,411,3
2,M6030 JERSEY SHIRT LANGARM,HELLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,389,389,19,378,11
3,M6030 JERSEY SHIRT LANGARM,PETROLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,18,406,8
4,M6030 JERSEY SHIRT LANGARM,AUBERGINE 2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,414,16,411,3

In [8]:
#The Planned Column is the number of planned productions to be able to deliver number of product OrderQuantity
#It will not be used, as the expectation within the scope of this project is to make more meaningful planning
#For this reason, the relevant column is being removed
dataFrame.drop('Planned', axis = 1, inplace = True)
dataFrame.head()

,Product,Color,ProductDetail,FabricCode,FabricDetail,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Print,Repair,Delivery,SecondQuality
0,M6030 JERSEY SHIRT LANGARM,PINIE,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,35,3,375,405,405,20,399,6
1,M6030 JERSEY SHIRT LANGARM,PFIRSICH,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,22,411,3
2,M6030 JERSEY SHIRT LANGARM,HELLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,389,389,19,378,11
3,M6030 JERSEY SHIRT LANGARM,PETROLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,18,406,8
4,M6030 JERSEY SHIRT LANGARM,AUBERGINE 2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,414,16,411,3

In [9]:
#Looking at the Quantity and Print columns, it is seen that they frequently take the same value
#For this reason, it is being checked whether they always get the same value
dataFrame[dataFrame['Quantity'] != dataFrame['Print']].shape

(0, 16)

In [10]:
#As can be see, there is no row satisfying the Quantity != Print Condition
#According to the dataset, these two columns mean the same feature
#One of the relevant columns is being removed
dataFrame.drop('Print', axis = 1, inplace = True)
dataFrame.head()

,Product,Color,ProductDetail,FabricCode,FabricDetail,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,M6030 JERSEY SHIRT LANGARM,PINIE,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,35,3,375,405,20,399,6
1,M6030 JERSEY SHIRT LANGARM,PFIRSICH,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,22,411,3
2,M6030 JERSEY SHIRT LANGARM,HELLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,389,19,378,11
3,M6030 JERSEY SHIRT LANGARM,PETROLBLAU,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,18,406,8
4,M6030 JERSEY SHIRT LANGARM,AUBERGINE 2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,125,150,4,65,3,375,414,16,411,3

In [11]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product        186 non-null    object
 1   Color          186 non-null    object
 2   ProductDetail  186 non-null    object
 3   FabricCode     186 non-null    object
 4   FabricDetail   186 non-null    object
 5   Weight         186 non-null    int64
 6   Width          186 non-null    object
 7   ProductPart    186 non-null    int64
 8   NotchLayer     186 non-null    object
 9   NotchQuantity  178 non-null    object
 10  OrderQuantity  186 non-null    int64
 11  Quantity       186 non-null    int64
 12  Repair         186 non-null    int64
 13  Delivery       186 non-null    int64
 14  SecondQuality  186 non-null    int64
dtypes: int64(7), object(8)
memory usage: 21.9+ KB

In [12]:
#Statistical information of dataFrame is being printed
dataFrame.describe()

,Weight,ProductPart,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,165.241935,4.801075,294.489247,317.209677,6.387097,309.311828,7.897849
std,36.999935,2.289388,113.160409,123.932912,4.987622,122.498051,6.454439
min,125.000000,2.000000,100.000000,110.000000,0.000000,112.000000,-2.000000
25%,125.000000,4.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,172.500000,4.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,190.000000,5.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,250.000000,14.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [13]:
#dataFrame cleaned of columns that will not be used is being saved as pkl file
dataFrame.to_pickle("../Data/NeddedColumns/FabricWaste.pkl")