# Fifth Data Preparation Process

In this notebook file, the dataset provided by the customer will be eddited for general purposes.

The ProductDetail feature will be examined in depth.

In [1]:
#Library is being imported
import pandas as pd

In [2]:
#Library version is being printed
print('pandas Version: ' + pd.__version__)

pandas Version: 1.5.2

In [3]:
#A pandas dataframe named as dataFrame is being created by reading the data pkl file created last process
dataFrame = pd.read_pickle("../Data/WithRelationalTables/FabricWasteColor.pkl")
dataFrame.head()

,ColorID,ProductDetail,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,18,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,375,405,20,399,6
1,19,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,22,411,3
2,6,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,389,19,378,11
3,20,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,18,406,8
4,2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,16,411,3

In [4]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ColorID          186 non-null    int64
 1   ProductDetail    186 non-null    object
 2   FabricCode       186 non-null    object
 3   FabricDetail     186 non-null    object
 4   IsManualProcess  186 non-null    bool
 5   Weight           186 non-null    int64
 6   Width            186 non-null    int64
 7   ProductPart      186 non-null    int64
 8   NotchLayer       186 non-null    int64
 9   NotchQuantity    186 non-null    int64
 10  OrderQuantity    186 non-null    int64
 11  Quantity         186 non-null    int64
 12  Repair           186 non-null    int64
 13  Delivery         186 non-null    int64
 14  SecondQuality    186 non-null    int64
dtypes: bool(1), int64(11), object(3)
memory usage: 20.7+ KB

In [5]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,ColorID,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,14.193548,165.241935,159.435484,4.801075,44.483871,2.467742,294.489247,317.209677,6.387097,309.295699,7.913978
std,9.653184,36.999935,15.936653,2.289388,21.042615,0.792896,113.160409,123.932912,4.987622,122.519425,6.432445
min,0.000000,125.000000,120.000000,2.000000,0.000000,0.000000,100.000000,110.000000,0.000000,110.000000,0.000000
25%,4.250000,125.000000,150.000000,4.000000,31.000000,2.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,14.000000,172.500000,160.000000,4.000000,39.000000,3.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,22.000000,190.000000,171.500000,5.000000,58.000000,3.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,32.000000,250.000000,180.000000,14.000000,111.000000,4.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [6]:
#Number of unique values of each column are being printed
dataFrame.nunique()

ColorID             33
ProductDetail       21
FabricCode           9
FabricDetail        12
IsManualProcess      2
Weight               6
Width                8
ProductPart         12
NotchLayer          31
NotchQuantity        5
OrderQuantity       37
Quantity           106
Repair              22
Delivery           131
SecondQuality       27
dtype: int64

In [7]:
#Too many unique values for a categorical attribute in ProductDetail column
#In order to use this feature effectively, the values in the column will be processed

#Unique ProductDetail are being printed
dataFrame['ProductDetail'].unique()

array(['KADIN T-SHIRT', 'KADIN PANTOLON', 'KADIN GOMLEK', 'KADIN ELBISE',
       'ERKEK PIJAMA / GECELIK', 'KADIN PIJAMA / GECELIK',
       'ERKEK T-SHIRT', 'KADIN ETEK', 'COCUK ELBISE', 'COCUK SWEAT',
       'KIZ COCUK SWEAT', 'KIZ COCUK PANTOLON', 'BEBEK T-SHIRT',
       'COCUK T-SHIRT', 'COCUK PANTOLON', 'KIZ COCUK ELBISE',
       'KIZ COCUK ETEK', 'KIZ COCUK T-SHIRT', 'BEBEK PANTOLON',
       'COCUK PIJAMA / GECELIK', 'COCUK AKSESUAR'], dtype=object)

In [8]:
#Now the values in the ProductDetail column in the dataFrame will be processed for extracting more features from it

#productDetailFrame that contains the detailed information of the values in the dataFrame ProductDetail column is being created
productDetailFrame = pd.DataFrame({
                            'ProductDetail' : dataFrame['ProductDetail'].unique()
                            })
productDetailFrame

             ProductDetail
0            KADIN T-SHIRT
1           KADIN PANTOLON
2             KADIN GOMLEK
3             KADIN ELBISE
4   ERKEK PIJAMA / GECELIK
5   KADIN PIJAMA / GECELIK
6            ERKEK T-SHIRT
7               KADIN ETEK
8             COCUK ELBISE
9              COCUK SWEAT
10         KIZ COCUK SWEAT
11      KIZ COCUK PANTOLON
12           BEBEK T-SHIRT
13           COCUK T-SHIRT
14          COCUK PANTOLON
15        KIZ COCUK ELBISE
16          KIZ COCUK ETEK
17       KIZ COCUK T-SHIRT
18          BEBEK PANTOLON
19  COCUK PIJAMA / GECELIK
20          COCUK AKSESUAR

In [9]:
#The function that will extract the Maturity information from the ProductDetail column is being defined
def ExtractMaturity(productDetail):
    #Çocuk means Child in Turkish
    if 'COCUK' in productDetail:
        return 'Child'
    #Bebek means Baby in Turkish
    elif 'BEBEK' in productDetail:
        return 'Baby'
    #Others are Adult
    else:
        return 'Adult'

In [10]:
#ExtractMaturity function is being applied for each value in the ProductDetail column
#and the results are being written to the Maturity column
productDetailFrame['Maturity'] = productDetailFrame['ProductDetail'].apply(lambda x : ExtractMaturity(x))
productDetailFrame

             ProductDetail Maturity
0            KADIN T-SHIRT    Adult
1           KADIN PANTOLON    Adult
2             KADIN GOMLEK    Adult
3             KADIN ELBISE    Adult
4   ERKEK PIJAMA / GECELIK    Adult
5   KADIN PIJAMA / GECELIK    Adult
6            ERKEK T-SHIRT    Adult
7               KADIN ETEK    Adult
8             COCUK ELBISE    Child
9              COCUK SWEAT    Child
10         KIZ COCUK SWEAT    Child
11      KIZ COCUK PANTOLON    Child
12           BEBEK T-SHIRT     Baby
13           COCUK T-SHIRT    Child
14          COCUK PANTOLON    Child
15        KIZ COCUK ELBISE    Child
16          KIZ COCUK ETEK    Child
17       KIZ COCUK T-SHIRT    Child
18          BEBEK PANTOLON     Baby
19  COCUK PIJAMA / GECELIK    Child
20          COCUK AKSESUAR    Child

In [11]:
#The function that will extract the Gender information from the ProductDetail column is being defined
def ExtractGender(productDetail):
    #Kadın and Kız denote female gender in Turkish
    if 'KADIN' in productDetail or 'KIZ' in productDetail:
        return 'Female'
    #Erkek denote male gender in Turkish
    elif 'ERKEK' in productDetail:
        return 'Male'
    #Others will be considered as Unisex
    else:
        return 'Unisex'

In [12]:
#ExtractGender function is being applied for each value in the ProductDetail column
#and the results are being written to the Gender column
productDetailFrame['Gender'] = productDetailFrame['ProductDetail'].apply(lambda x : ExtractGender(x))
productDetailFrame

             ProductDetail Maturity  Gender
0            KADIN T-SHIRT    Adult  Female
1           KADIN PANTOLON    Adult  Female
2             KADIN GOMLEK    Adult  Female
3             KADIN ELBISE    Adult  Female
4   ERKEK PIJAMA / GECELIK    Adult    Male
5   KADIN PIJAMA / GECELIK    Adult  Female
6            ERKEK T-SHIRT    Adult    Male
7               KADIN ETEK    Adult  Female
8             COCUK ELBISE    Child  Unisex
9              COCUK SWEAT    Child  Unisex
10         KIZ COCUK SWEAT    Child  Female
11      KIZ COCUK PANTOLON    Child  Female
12           BEBEK T-SHIRT     Baby  Unisex
13           COCUK T-SHIRT    Child  Unisex
14          COCUK PANTOLON    Child  Unisex
15        KIZ COCUK ELBISE    Child  Female
16          KIZ COCUK ETEK    Child  Female
17       KIZ COCUK T-SHIRT    Child  Female
18          BEBEK PANTOLON     Baby  Unisex
19  COCUK PIJAMA / GECELIK    Child  Unisex
20          COCUK AKSESUAR    Child  Unisex

In [13]:
#The function that will extract the ProductType information from the ProductDetail column is being defined
def ExtractProductType(productDetail):
    if 'T-SHIRT' in productDetail:
        return 'T-Shirt'
    #Pantolon means Pant in Turkish
    elif 'PANTOLON' in productDetail:
        return 'Pant'
    #Gömlek means Shirt in Turkish
    elif 'GOMLEK' in productDetail:
        return 'Shirt'
    #Elbise means Dress in Turkish
    elif 'ELBISE' in productDetail:
        return 'Dress'
    #Pijama  means Pyjamas in Turkish
    elif 'PIJAMA' in productDetail:
        return 'Pyjamas'
    #Etek means Skirt in Turkish
    elif 'ETEK' in productDetail:
        return 'Skirt'
    elif 'SWEAT' in productDetail:
        return 'Sweatshirt'
    #Aksesuar means Accessory in Turkish
    elif 'AKSESUAR' in productDetail:
        return 'Accessory'
    else:
        return None

In [14]:
#ExtractProductType function is being applied for each value in the ProductDetail column
#and the results are being written to the ProductType column
productDetailFrame['ProductType'] = productDetailFrame['ProductDetail'].apply(lambda x : ExtractProductType(x))
productDetailFrame

             ProductDetail Maturity  Gender ProductType
0            KADIN T-SHIRT    Adult  Female     T-Shirt
1           KADIN PANTOLON    Adult  Female        Pant
2             KADIN GOMLEK    Adult  Female       Shirt
3             KADIN ELBISE    Adult  Female       Dress
4   ERKEK PIJAMA / GECELIK    Adult    Male     Pyjamas
5   KADIN PIJAMA / GECELIK    Adult  Female     Pyjamas
6            ERKEK T-SHIRT    Adult    Male     T-Shirt
7               KADIN ETEK    Adult  Female       Skirt
8             COCUK ELBISE    Child  Unisex       Dress
9              COCUK SWEAT    Child  Unisex  Sweatshirt
10         KIZ COCUK SWEAT    Child  Female  Sweatshirt
11      KIZ COCUK PANTOLON    Child  Female        Pant
12           BEBEK T-SHIRT     Baby  Unisex     T-Shirt
13           COCUK T-SHIRT    Child  Unisex     T-Shirt
14          COCUK PANTOLON    Child  Unisex        Pant
15        KIZ COCUK ELBISE    Child  Female       Dress
16          KIZ COCUK ETEK    Child  Female       Skirt
17       KIZ COCUK T-SHIRT    Child  Female     T-Shirt
18          BEBEK PANTOLON     Baby  Unisex        Pant
19  COCUK PIJAMA / GECELIK    Child  Unisex     Pyjamas
20          COCUK AKSESUAR    Child  Unisex   Accessory

In [15]:
#unique value counts for columns in productDetailFrame are being printed
productDetailFrame.nunique()

ProductDetail    21
Maturity          3
Gender            3
ProductType       8
dtype: int64

In [16]:
#When the unique value counts are examined, it can be seen that there are 8 unique values for the ProductType feature
#When the data is examined, it can be noticed that more general categories can be created for these categories

#The function that will extract the ProductTypeCategory information from the ProductType column is being defined
def ExtractProductTypeCategory(ProductType):
    if 'T-Shirt' in ProductType or 'Shirt' in ProductType or 'Sweatshirt' in ProductType:
        return 'Top'
    elif 'Pant' in ProductType or 'Skirt' in ProductType:
        return 'Leg'
    elif 'Dress' in ProductType or 'Pyjamas' in ProductType:
        return 'Full'
    else:
        return 'Other'

In [17]:
#ExtractProductTypeCategory function is being applied for each value in the ProductType column
#and the results are being written to the ProductTypeCategory column
productDetailFrame['ProductTypeCategory'] = productDetailFrame['ProductType'].apply(lambda x : ExtractProductTypeCategory(x))
productDetailFrame

             ProductDetail Maturity  Gender ProductType ProductTypeCategory
0            KADIN T-SHIRT    Adult  Female     T-Shirt                 Top
1           KADIN PANTOLON    Adult  Female        Pant                 Leg
2             KADIN GOMLEK    Adult  Female       Shirt                 Top
3             KADIN ELBISE    Adult  Female       Dress                Full
4   ERKEK PIJAMA / GECELIK    Adult    Male     Pyjamas                Full
5   KADIN PIJAMA / GECELIK    Adult  Female     Pyjamas                Full
6            ERKEK T-SHIRT    Adult    Male     T-Shirt                 Top
7               KADIN ETEK    Adult  Female       Skirt                 Leg
8             COCUK ELBISE    Child  Unisex       Dress                Full
9              COCUK SWEAT    Child  Unisex  Sweatshirt                 Top
10         KIZ COCUK SWEAT    Child  Female  Sweatshirt                 Top
11      KIZ COCUK PANTOLON    Child  Female        Pant                 Leg
12           BEBEK T-SHIRT     Baby  Unisex     T-Shirt                 Top
13           COCUK T-SHIRT    Child  Unisex     T-Shirt                 Top
14          COCUK PANTOLON    Child  Unisex        Pant                 Leg
15        KIZ COCUK ELBISE    Child  Female       Dress                Full
16          KIZ COCUK ETEK    Child  Female       Skirt                 Leg
17       KIZ COCUK T-SHIRT    Child  Female     T-Shirt                 Top
18          BEBEK PANTOLON     Baby  Unisex        Pant                 Leg
19  COCUK PIJAMA / GECELIK    Child  Unisex     Pyjamas                Full
20          COCUK AKSESUAR    Child  Unisex   Accessory               Other

In [18]:
#Since all information about ProductDetails is kept in the productDetailFrame,
#it will bi sufficient to keep foreign key values of ProductDetails representing the productDetailFrame data in the dataFrame

#dataFrame ProductDetail column is being recreated as productDetailFrame indexes
dataFrame['ProductDetail'] = dataFrame['ProductDetail'].apply(
    lambda x : productDetailFrame.index[productDetailFrame['ProductDetail'] == x].tolist()[0])
dataFrame.head()

,ColorID,ProductDetail,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,18,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,375,405,20,399,6
1,19,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,22,411,3
2,6,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,389,19,378,11
3,20,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,18,406,8
4,2,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,16,411,3

In [19]:
#ProductDetail column is being renamed as ProductDetailID
dataFrame.rename(columns = {'ProductDetail' : 'ProductDetailID'}, inplace = True)
dataFrame.head()

,ColorID,ProductDetailID,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,18,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,375,405,20,399,6
1,19,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,22,411,3
2,6,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,389,19,378,11
3,20,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,18,406,8
4,2,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,16,411,3

In [20]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ColorID          186 non-null    int64
 1   ProductDetailID  186 non-null    int64
 2   FabricCode       186 non-null    object
 3   FabricDetail     186 non-null    object
 4   IsManualProcess  186 non-null    bool
 5   Weight           186 non-null    int64
 6   Width            186 non-null    int64
 7   ProductPart      186 non-null    int64
 8   NotchLayer       186 non-null    int64
 9   NotchQuantity    186 non-null    int64
 10  OrderQuantity    186 non-null    int64
 11  Quantity         186 non-null    int64
 12  Repair           186 non-null    int64
 13  Delivery         186 non-null    int64
 14  SecondQuality    186 non-null    int64
dtypes: bool(1), int64(12), object(2)
memory usage: 20.7+ KB

In [21]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,ColorID,ProductDetailID,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,14.193548,5.580645,165.241935,159.435484,4.801075,44.483871,2.467742,294.489247,317.209677,6.387097,309.295699,7.913978
std,9.653184,6.526988,36.999935,15.936653,2.289388,21.042615,0.792896,113.160409,123.932912,4.987622,122.519425,6.432445
min,0.000000,0.000000,125.000000,120.000000,2.000000,0.000000,0.000000,100.000000,110.000000,0.000000,110.000000,0.000000
25%,4.250000,0.000000,125.000000,150.000000,4.000000,31.000000,2.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,14.000000,1.000000,172.500000,160.000000,4.000000,39.000000,3.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,22.000000,12.000000,190.000000,171.500000,5.000000,58.000000,3.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,32.000000,20.000000,250.000000,180.000000,14.000000,111.000000,4.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [22]:
#Information of productDetailFrame is being printed
productDetailFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ProductDetail        21 non-null     object
 1   Maturity             21 non-null     object
 2   Gender               21 non-null     object
 3   ProductType          21 non-null     object
 4   ProductTypeCategory  21 non-null     object
dtypes: object(5)
memory usage: 968.0+ bytes

In [23]:
#Statistical information of productDetailFrame is being printed
productDetailFrame.describe()

        ProductDetail Maturity  Gender ProductType ProductTypeCategory
count              21       21      21          21                  21
unique             21        3       3           8                   4
top     KADIN T-SHIRT    Child  Female     T-Shirt                 Top
freq                1       11      11           5                   8

In [24]:
#dataFrame and relational productDetailFrame are being saved as pkl files
dataFrame.to_pickle("../Data/WithRelationalTables/FabricWasteProductDetail.pkl")
productDetailFrame.to_pickle("../Data/WithRelationalTables/ProductDetail.pkl")