# Sixth Data Preparation Process

In this notebook file, the dataset provided by the customer will be eddited for general purposes.

FabricCode and FabricDetail features will be examined in depth.

In [1]:
#Library is being imported
import pandas as pd

In [2]:
#Library version is being printed
print('pandas Version: ' + pd.__version__)

pandas Version: 1.5.2

In [3]:
#A pandas dataframe named as dataFrame is being created by reading the data pkl file created last process
dataFrame = pd.read_pickle("../Data/WithRelationalTables/FabricWasteProductDetail.pkl")
dataFrame.head()

,ColorID,ProductDetailID,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,18,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,375,405,20,399,6
1,19,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,22,411,3
2,6,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,389,19,378,11
3,20,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,18,406,8
4,2,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,16,411,3

In [4]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ColorID          186 non-null    int64
 1   ProductDetailID  186 non-null    int64
 2   FabricCode       186 non-null    object
 3   FabricDetail     186 non-null    object
 4   IsManualProcess  186 non-null    bool
 5   Weight           186 non-null    int64
 6   Width            186 non-null    int64
 7   ProductPart      186 non-null    int64
 8   NotchLayer       186 non-null    int64
 9   NotchQuantity    186 non-null    int64
 10  OrderQuantity    186 non-null    int64
 11  Quantity         186 non-null    int64
 12  Repair           186 non-null    int64
 13  Delivery         186 non-null    int64
 14  SecondQuality    186 non-null    int64
dtypes: bool(1), int64(12), object(2)
memory usage: 20.7+ KB

In [5]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,ColorID,ProductDetailID,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,14.193548,5.580645,165.241935,159.435484,4.801075,44.483871,2.467742,294.489247,317.209677,6.387097,309.295699,7.913978
std,9.653184,6.526988,36.999935,15.936653,2.289388,21.042615,0.792896,113.160409,123.932912,4.987622,122.519425,6.432445
min,0.000000,0.000000,125.000000,120.000000,2.000000,0.000000,0.000000,100.000000,110.000000,0.000000,110.000000,0.000000
25%,4.250000,0.000000,125.000000,150.000000,4.000000,31.000000,2.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,14.000000,1.000000,172.500000,160.000000,4.000000,39.000000,3.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,22.000000,12.000000,190.000000,171.500000,5.000000,58.000000,3.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,32.000000,20.000000,250.000000,180.000000,14.000000,111.000000,4.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [6]:
#Number of unique values of each column are being printed
dataFrame.nunique()

ColorID             33
ProductDetailID     21
FabricCode           9
FabricDetail        12
IsManualProcess      2
Weight               6
Width                8
ProductPart         12
NotchLayer          31
NotchQuantity        5
OrderQuantity       37
Quantity           106
Repair              22
Delivery           131
SecondQuality       27
dtype: int64

In [7]:
#The FabricCode feature can be thought of as the ID of the FabricDetail feature
#In this case, the number of unique values must be equal
#However, when the unique valu numbers examined, it can be seen that
#the FabricCode column has 9 unique values and
#the FabricDetail column has 12 unique values
#This is an unexpected situation and needs to be investigated

#FabricDetail values are being printed for each FabricCode value
pd.DataFrame(dataFrame.groupby(['FabricCode', 'FabricDetail']).size(), columns=['NumberOfRow'])

                                                               NumberOfRow
FabricCode FabricDetail
2IN007     NE 30/1 30/1 PNY PNY - INTERLOK DOUBLE FACE A.E...            7
2RB201     NE 30/1 PNY RAPORLU   - RIBANA  A.EN 34 20 E 17...            1
           NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 17...           10
           NE 30/1 PNY RAPORLU  - RIBANA  A.EN 34 20 E 175...            1
           NE 30/1 PNY RAPORLU -   RIBANA  A.EN 34 20 E 17...            4
2SP021     NE 40/1 PNY - SUPREM A.EN 32 28 125 G/M2 %100 P...           40
2SP033     NE 20/1 PNY - SUPREM A.EN 32 22 190 G/M2 %100 P...           31
2SP050     NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 %...           34
2SP061     NE 30/1 PNY 40DE - SUPREM A.EN 32 28 190 G/M2 %...           30
2SP309     NE 30/1 PNY - SUPREM A.EN 32 28 170 G/M2 %100 P...           10
2SP388     NM 26/1  ISLAK CEKIM - - SUPREM   LOT  :33K346 ...            9
2SP464     NE 12/1 KRD - SUPREM A. EN 34-14 235 GR/M2  %55...            9

In [8]:
#When the data is examined, it can be seen that there are 4 different FabricDetail values for the 2RB201 FabricCode value
#Although they look the same when printed in DataFrame,
#there must be differences hidden by formatting method used in printing process

#FabricDetail values, which is FabricCode 2RB201, are being printed in its raw form for investigate differences
dataFrame[dataFrame['FabricCode'] == '2RB201']['FabricDetail'].values

array(['NE 30/1 PNY RAPORLU   - RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU -   RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU -   RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU -   RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU -   RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  - RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           ',
       'NE 30/1 PNY RAPORLU  -  RIBANA  A.EN 34 20 E 175  G/M2 % 100 PAM  KUMAS           '],
      dtype=object)

In [9]:
#When the results are examined, it can be seen that the difference is due to the whitespaces between characters
#To solve the problem, multiple whitespaces next to each other are made into singele whitespaces 
#then leading and trailing whitespaces are deleted
#Since this process will transform the data smoother form without breaking its structure,
#it is being applied not only the rows with FabricCode 2RB201, bu to entire column
dataFrame['FabricDetail'] = dataFrame['FabricDetail'].replace(r'\s+', ' ', regex = True).str.strip()
dataFrame.head()

,ColorID,ProductDetailID,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,18,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,375,405,20,399,6
1,19,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,22,411,3
2,6,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,389,19,378,11
3,20,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,18,406,8
4,2,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,375,414,16,411,3

In [10]:
#FabricDetail values, which is FabricCode 2RB201, are being printed in its raw form
dataFrame[dataFrame['FabricCode'] == '2RB201']['FabricDetail'].values

array(['NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS',
       'NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G/M2 % 100 PAM KUMAS'],
      dtype=object)

In [11]:
#FabricDetail values are being printed for each FabricCode value
pd.DataFrame(dataFrame.groupby(['FabricCode', 'FabricDetail']).size(), columns=['NumberOfRow'])

                                                               NumberOfRow
FabricCode FabricDetail
2IN007     NE 30/1 30/1 PNY PNY - INTERLOK DOUBLE FACE A.E...            7
2RB201     NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 G...           16
2SP021     NE 40/1 PNY - SUPREM A.EN 32 28 125 G/M2 %100 P...           40
2SP033     NE 20/1 PNY - SUPREM A.EN 32 22 190 G/M2 %100 P...           31
2SP050     NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 %...           34
2SP061     NE 30/1 PNY 40DE - SUPREM A.EN 32 28 190 G/M2 %...           30
2SP309     NE 30/1 PNY - SUPREM A.EN 32 28 170 G/M2 %100 P...           10
2SP388     NM 26/1 ISLAK CEKIM - - SUPREM LOT :33K346 008 ...            9
2SP464     NE 12/1 KRD - SUPREM A. EN 34-14 235 GR/M2 %55 ...            9

In [12]:
#fabricDetailFrame containing FabricCode - FabricDetail pairs is being created 
fabricDetailFrame = pd.DataFrame(dataFrame.groupby(['FabricCode', 'FabricDetail']).size()).reset_index().drop([0], axis = 1)
fabricDetailFrame

  FabricCode                                       FabricDetail
0     2IN007  NE 30/1 30/1 PNY PNY - INTERLOK DOUBLE FACE A....
1     2RB201  NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 ...
2     2SP021  NE 40/1 PNY - SUPREM A.EN 32 28 125 G/M2 %100 ...
3     2SP033  NE 20/1 PNY - SUPREM A.EN 32 22 190 G/M2 %100 ...
4     2SP050  NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...
5     2SP061  NE 30/1 PNY 40DE - SUPREM A.EN 32 28 190 G/M2 ...
6     2SP309  NE 30/1 PNY - SUPREM A.EN 32 28 170 G/M2 %100 ...
7     2SP388  NM 26/1 ISLAK CEKIM - - SUPREM LOT :33K346 008...
8     2SP464  NE 12/1 KRD - SUPREM A. EN 34-14 235 GR/M2 %55...

In [13]:
#The function that will extract the FabricType information from the FabricDetail column is being defined
def ExtractFabricType(fabricDetail):
    if 'SUPREM' in fabricDetail:
        return 'Single Jersey'
    elif 'RIBANA' in fabricDetail:
        return 'Ribana'
    elif 'INTERLOK' in fabricDetail:
        return 'Interlock'

In [14]:
#ExtractFabricType function is being applied for each value in the FabricDetail column
#and the results are being written to the FabricType column
fabricDetailFrame['FabricType'] = fabricDetailFrame['FabricDetail'].apply(lambda x : ExtractFabricType(x))
fabricDetailFrame

  FabricCode                                       FabricDetail     FabricType
0     2IN007  NE 30/1 30/1 PNY PNY - INTERLOK DOUBLE FACE A....      Interlock
1     2RB201  NE 30/1 PNY RAPORLU - RIBANA A.EN 34 20 E 175 ...         Ribana
2     2SP021  NE 40/1 PNY - SUPREM A.EN 32 28 125 G/M2 %100 ...  Single Jersey
3     2SP033  NE 20/1 PNY - SUPREM A.EN 32 22 190 G/M2 %100 ...  Single Jersey
4     2SP050  NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...  Single Jersey
5     2SP061  NE 30/1 PNY 40DE - SUPREM A.EN 32 28 190 G/M2 ...  Single Jersey
6     2SP309  NE 30/1 PNY - SUPREM A.EN 32 28 170 G/M2 %100 ...  Single Jersey
7     2SP388  NM 26/1 ISLAK CEKIM - - SUPREM LOT :33K346 008...  Single Jersey
8     2SP464  NE 12/1 KRD - SUPREM A. EN 34-14 235 GR/M2 %55...  Single Jersey

In [15]:
#Actually more features can be extracted from FabricDetail column
#Since this notebook file is part of the preliminary analysis, a more detailed analysis will not be done in this notebook

#FabricDetail column is being removed from dataFrame
dataFrame.drop(['FabricDetail'], axis = 1, inplace = True)
dataFrame.head()

,ColorID,ProductDetailID,FabricCode,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
0,18,0,2SP050,False,125,150,4,35,3,375,405,20,399,6
1,19,0,2SP050,False,125,150,4,65,3,375,414,22,411,3
2,6,0,2SP050,False,125,150,4,65,3,375,389,19,378,11
3,20,0,2SP050,False,125,150,4,65,3,375,414,18,406,8
4,2,0,2SP050,False,125,150,4,65,3,375,414,16,411,3

In [16]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ColorID          186 non-null    int64
 1   ProductDetailID  186 non-null    int64
 2   FabricCode       186 non-null    object
 3   IsManualProcess  186 non-null    bool
 4   Weight           186 non-null    int64
 5   Width            186 non-null    int64
 6   ProductPart      186 non-null    int64
 7   NotchLayer       186 non-null    int64
 8   NotchQuantity    186 non-null    int64
 9   OrderQuantity    186 non-null    int64
 10  Quantity         186 non-null    int64
 11  Repair           186 non-null    int64
 12  Delivery         186 non-null    int64
 13  SecondQuality    186 non-null    int64
dtypes: bool(1), int64(12), object(1)
memory usage: 19.2+ KB

In [17]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,ColorID,ProductDetailID,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,SecondQuality
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,14.193548,5.580645,165.241935,159.435484,4.801075,44.483871,2.467742,294.489247,317.209677,6.387097,309.295699,7.913978
std,9.653184,6.526988,36.999935,15.936653,2.289388,21.042615,0.792896,113.160409,123.932912,4.987622,122.519425,6.432445
min,0.000000,0.000000,125.000000,120.000000,2.000000,0.000000,0.000000,100.000000,110.000000,0.000000,110.000000,0.000000
25%,4.250000,0.000000,125.000000,150.000000,4.000000,31.000000,2.000000,206.250000,224.000000,3.000000,217.000000,4.000000
50%,14.000000,1.000000,172.500000,160.000000,4.000000,39.000000,3.000000,250.000000,272.000000,6.000000,265.000000,6.000000
75%,22.000000,12.000000,190.000000,171.500000,5.000000,58.000000,3.000000,380.000000,414.000000,8.000000,407.500000,10.000000
max,32.000000,20.000000,250.000000,180.000000,14.000000,111.000000,4.000000,640.000000,698.000000,30.000000,690.000000,38.000000

In [18]:
#Information of fabricDetailFrame is being printed
fabricDetailFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FabricCode    9 non-null      object
 1   FabricDetail  9 non-null      object
 2   FabricType    9 non-null      object
dtypes: object(3)
memory usage: 344.0+ bytes

In [19]:
#Statistical information of fabricDetailFrame is being printed
fabricDetailFrame.describe()

,FabricCode,FabricDetail,FabricType
count,9,9,9
unique,9,9,3
top,2IN007,NE 30/1 30/1 PNY PNY - INTERLOK DOUBLE FACE A....,Single Jersey
freq,1,1,7

In [20]:
#Since FabricCode is can be used as id for FabricDetail, there is no need to create a foreign key for FabricDetail

#dataFrame and relational fabricDetailFrame are being saved as pkl files
dataFrame.to_pickle("../Data/WithRelationalTables/FabricWasteFabricDetail.pkl")
fabricDetailFrame.to_pickle("../Data/WithRelationalTables/FabricDetail.pkl")