# Fifth Data Preparation Process

In this notebook file, the dataset provided by the customer will be eddited for general purposes.

The ProductDetail feature will be examined in depth.

In [1]:
#Library is being imported
import pandas as pd

In [2]:
#Library version is being printed
print('pandas Version: ' + pd.__version__)

pandas Version: 1.5.2

In [3]:
#A pandas dataframe named as dataFrame is being created by reading the data pkl file created last process
dataFrame = pd.read_pickle("../Data/WithRelationalTables/FabricWasteColor.pkl")
dataFrame.head()

,ColorID,ProductDetail,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,...,Quantity,Repair,Delivery,PrintError,SewingError,FabricStain,FabricError,EmbroideryError,MeasureError,SecondQuality
0,18,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,...,405,20,399,4,0,1,1,0,0,6
1,19,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,22,411,0,2,1,0,0,0,3
2,6,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,389,19,378,1,5,2,1,1,1,11
3,20,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,18,406,0,4,2,2,0,0,8
4,2,KADIN T-SHIRT,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,16,411,0,3,0,0,0,0,3

In [4]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 206 entries, 0 to 208
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ColorID          206 non-null    int64
 1   ProductDetail    206 non-null    object
 2   FabricCode       206 non-null    object
 3   FabricDetail     206 non-null    object
 4   IsManualProcess  206 non-null    bool
 5   Weight           206 non-null    int64
 6   Width            206 non-null    int64
 7   ProductPart      206 non-null    int64
 8   NotchLayer       206 non-null    int64
 9   NotchQuantity    206 non-null    int64
 10  OrderQuantity    206 non-null    int64
 11  Quantity         206 non-null    int64
 12  Repair           206 non-null    int64
 13  Delivery         206 non-null    int64
 14  PrintError       206 non-null    int64
 15  SewingError      206 non-null    int64
 16  FabricStain      206 non-null    int64
 17  FabricError      206 non-null    int64
 18  EmbroideryError  206 non-null    int64
 19  MeasureError     206 non-null    int64
 20  SecondQuality    206 non-null    int64
dtypes: bool(1), int64(17), object(3)
memory usage: 34.0+ KB

In [5]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,ColorID,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,PrintError,SewingError,FabricStain,FabricError,EmbroideryError,MeasureError,SecondQuality
count,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000
mean,16.796117,171.601942,161.451456,4.902913,64.621359,2.864078,528.956311,574.305825,8.179612,559.199029,4.917476,6.786408,0.635922,2.145631,0.228155,0.393204,15.106796
std,11.881413,45.318459,16.988808,2.433564,73.558421,1.571382,812.807992,891.308093,8.979205,866.214970,18.322796,9.375266,2.653754,4.737824,1.246021,1.330964,30.253696
min,0.000000,125.000000,120.000000,2.000000,0.000000,0.000000,150.000000,148.000000,0.000000,134.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,5.000000,125.000000,150.000000,4.000000,33.000000,2.000000,210.000000,225.750000,3.000000,220.250000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000
50%,16.000000,175.000000,165.000000,4.000000,44.000000,3.000000,275.000000,289.000000,6.000000,284.500000,0.000000,4.000000,0.000000,1.000000,0.000000,0.000000,7.500000
75%,26.000000,190.000000,172.000000,5.000000,66.750000,3.000000,400.000000,443.500000,9.000000,437.750000,2.000000,9.000000,0.000000,2.000000,0.000000,0.000000,12.750000
max,47.000000,320.000000,195.000000,14.000000,610.000000,14.000000,6000.000000,6605.000000,78.000000,6469.000000,201.000000,88.000000,29.000000,45.000000,15.000000,10.000000,311.000000

In [6]:
#Number of unique values of each column are being printed
dataFrame.nunique()

ColorID             48
ProductDetail       24
FabricCode          19
FabricDetail        19
IsManualProcess      2
Weight              11
Width               12
ProductPart         12
NotchLayer          47
NotchQuantity       10
OrderQuantity       56
Quantity           126
Repair              30
Delivery           152
PrintError          29
SewingError         31
FabricStain          9
FabricError         16
EmbroideryError      7
MeasureError         8
SecondQuality       43
dtype: int64

In [7]:
#Too many unique values for a categorical attribute in ProductDetail column
#In order to use this feature effectively, the values in the column will be processed

#Unique ProductDetail are being printed
dataFrame['ProductDetail'].unique()

array(['KADIN T-SHIRT', 'KADIN PANTOLON', 'KADIN GOMLEK', 'KADIN ELBISE',
       'ERKEK PIJAMA / GECELIK', 'KADIN PIJAMA / GECELIK',
       'ERKEK T-SHIRT', 'KADIN ETEK', 'COCUK ELBISE', 'COCUK SWEAT',
       'KIZ COCUK SWEAT', 'BEBEK T-SHIRT', 'COCUK T-SHIRT',
       'KIZ COCUK PANTOLON', 'COCUK PANTOLON', 'KIZ COCUK ELBISE',
       'KIZ COCUK ETEK', 'KIZ COCUK T-SHIRT', 'BEBEK PANTOLON',
       'COCUK PIJAMA / GECELIK', 'ERKEK SWEAT', 'ERKEK CEKET',
       'BAYAN T-SHIRT', 'BAYAN SWEAT'], dtype=object)

In [8]:
#Now the values in the ProductDetail column in the dataFrame will be processed for extracting more features from it

#productDetailFrame that contains the detailed information of the values in the dataFrame ProductDetail column is being created
productDetailFrame = pd.DataFrame({
                            'ProductDetail' : dataFrame['ProductDetail'].unique()
                            })
productDetailFrame

             ProductDetail
0            KADIN T-SHIRT
1           KADIN PANTOLON
2             KADIN GOMLEK
3             KADIN ELBISE
4   ERKEK PIJAMA / GECELIK
5   KADIN PIJAMA / GECELIK
6            ERKEK T-SHIRT
7               KADIN ETEK
8             COCUK ELBISE
9              COCUK SWEAT
10         KIZ COCUK SWEAT
11           BEBEK T-SHIRT
12           COCUK T-SHIRT
13      KIZ COCUK PANTOLON
14          COCUK PANTOLON
15        KIZ COCUK ELBISE
16          KIZ COCUK ETEK
17       KIZ COCUK T-SHIRT
18          BEBEK PANTOLON
19  COCUK PIJAMA / GECELIK
20             ERKEK SWEAT
21             ERKEK CEKET
22           BAYAN T-SHIRT
23             BAYAN SWEAT

In [9]:
#The function that will extract the Maturity information from the ProductDetail column is being defined
def ExtractMaturity(productDetail):
    #Ã‡ocuk means Child in Turkish
    if 'COCUK' in productDetail:
        return 'Child'
    #Bebek means Baby in Turkish
    elif 'BEBEK' in productDetail:
        return 'Baby'
    #Others are Adult
    else:
        return 'Adult'

In [10]:
#ExtractMaturity function is being applied for each value in the ProductDetail column
#and the results are being written to the Maturity column
productDetailFrame['Maturity'] = productDetailFrame['ProductDetail'].apply(lambda x : ExtractMaturity(x))
productDetailFrame

             ProductDetail Maturity
0            KADIN T-SHIRT    Adult
1           KADIN PANTOLON    Adult
2             KADIN GOMLEK    Adult
3             KADIN ELBISE    Adult
4   ERKEK PIJAMA / GECELIK    Adult
5   KADIN PIJAMA / GECELIK    Adult
6            ERKEK T-SHIRT    Adult
7               KADIN ETEK    Adult
8             COCUK ELBISE    Child
9              COCUK SWEAT    Child
10         KIZ COCUK SWEAT    Child
11           BEBEK T-SHIRT     Baby
12           COCUK T-SHIRT    Child
13      KIZ COCUK PANTOLON    Child
14          COCUK PANTOLON    Child
15        KIZ COCUK ELBISE    Child
16          KIZ COCUK ETEK    Child
17       KIZ COCUK T-SHIRT    Child
18          BEBEK PANTOLON     Baby
19  COCUK PIJAMA / GECELIK    Child
20             ERKEK SWEAT    Adult
21             ERKEK CEKET    Adult
22           BAYAN T-SHIRT    Adult
23             BAYAN SWEAT    Adult

In [11]:
#The function that will extract the Gender information from the ProductDetail column is being defined
def ExtractGender(productDetail):
    #KadÄ±n, KÄ±z and Bayan denote female gender in Turkish,
    #Also Elbise denote dress and is only used for women's clothing
    if 'KADIN' in productDetail or 'KIZ' in productDetail or 'BAYAN' in productDetail or 'ELBISE' in productDetail:
        return 'Female'
    #Erkek denote male gender in Turkish
    elif 'ERKEK' in productDetail:
        return 'Male'
    #Others will be considered as Unisex
    else:
        return 'Unisex'

In [12]:
#ExtractGender function is being applied for each value in the ProductDetail column
#and the results are being written to the Gender column
productDetailFrame['Gender'] = productDetailFrame['ProductDetail'].apply(lambda x : ExtractGender(x))
productDetailFrame

             ProductDetail Maturity  Gender
0            KADIN T-SHIRT    Adult  Female
1           KADIN PANTOLON    Adult  Female
2             KADIN GOMLEK    Adult  Female
3             KADIN ELBISE    Adult  Female
4   ERKEK PIJAMA / GECELIK    Adult    Male
5   KADIN PIJAMA / GECELIK    Adult  Female
6            ERKEK T-SHIRT    Adult    Male
7               KADIN ETEK    Adult  Female
8             COCUK ELBISE    Child  Female
9              COCUK SWEAT    Child  Unisex
10         KIZ COCUK SWEAT    Child  Female
11           BEBEK T-SHIRT     Baby  Unisex
12           COCUK T-SHIRT    Child  Unisex
13      KIZ COCUK PANTOLON    Child  Female
14          COCUK PANTOLON    Child  Unisex
15        KIZ COCUK ELBISE    Child  Female
16          KIZ COCUK ETEK    Child  Female
17       KIZ COCUK T-SHIRT    Child  Female
18          BEBEK PANTOLON     Baby  Unisex
19  COCUK PIJAMA / GECELIK    Child  Unisex
20             ERKEK SWEAT    Adult    Male
21             ERKEK CEKET    Adult    Male
22           BAYAN T-SHIRT    Adult  Female
23             BAYAN SWEAT    Adult  Female

In [13]:
#The function that will extract the ProductType information from the ProductDetail column is being defined
def ExtractProductType(productDetail):
    if 'T-SHIRT' in productDetail:
        return 'T-Shirt'
    #Pantolon means Pant in Turkish
    elif 'PANTOLON' in productDetail:
        return 'Pant'
    #GÃ¶mlek means Shirt in Turkish
    elif 'GOMLEK' in productDetail:
        return 'Shirt'
    #Elbise means Dress in Turkish
    elif 'ELBISE' in productDetail:
        return 'Dress'
    #Pijama  means Pyjamas in Turkish
    elif 'PIJAMA' in productDetail:
        return 'Pyjamas'
    #Etek means Skirt in Turkish
    elif 'ETEK' in productDetail:
        return 'Skirt'
    elif 'SWEAT' in productDetail:
        return 'Sweatshirt'
    #Ceket means Coat or Jacket in Turkish
    elif 'CEKET' in productDetail:
        return 'Coat'
    else:
        return None

In [14]:
#ExtractProductType function is being applied for each value in the ProductDetail column
#and the results are being written to the ProductType column
productDetailFrame['ProductType'] = productDetailFrame['ProductDetail'].apply(lambda x : ExtractProductType(x))
productDetailFrame

             ProductDetail Maturity  Gender ProductType
0            KADIN T-SHIRT    Adult  Female     T-Shirt
1           KADIN PANTOLON    Adult  Female        Pant
2             KADIN GOMLEK    Adult  Female       Shirt
3             KADIN ELBISE    Adult  Female       Dress
4   ERKEK PIJAMA / GECELIK    Adult    Male     Pyjamas
5   KADIN PIJAMA / GECELIK    Adult  Female     Pyjamas
6            ERKEK T-SHIRT    Adult    Male     T-Shirt
7               KADIN ETEK    Adult  Female       Skirt
8             COCUK ELBISE    Child  Female       Dress
9              COCUK SWEAT    Child  Unisex  Sweatshirt
10         KIZ COCUK SWEAT    Child  Female  Sweatshirt
11           BEBEK T-SHIRT     Baby  Unisex     T-Shirt
12           COCUK T-SHIRT    Child  Unisex     T-Shirt
13      KIZ COCUK PANTOLON    Child  Female        Pant
14          COCUK PANTOLON    Child  Unisex        Pant
15        KIZ COCUK ELBISE    Child  Female       Dress
16          KIZ COCUK ETEK    Child  Female       Skirt
17       KIZ COCUK T-SHIRT    Child  Female     T-Shirt
18          BEBEK PANTOLON     Baby  Unisex        Pant
19  COCUK PIJAMA / GECELIK    Child  Unisex     Pyjamas
20             ERKEK SWEAT    Adult    Male  Sweatshirt
21             ERKEK CEKET    Adult    Male        Coat
22           BAYAN T-SHIRT    Adult  Female     T-Shirt
23             BAYAN SWEAT    Adult  Female  Sweatshirt

In [15]:
#unique value counts for columns in productDetailFrame are being printed
productDetailFrame.nunique()

ProductDetail    24
Maturity          3
Gender            3
ProductType       8
dtype: int64

In [16]:
#When the unique value counts are examined, it can be seen that there are 8 unique values for the ProductType feature
#When the data is examined, it can be noticed that more general categories can be created for these categories

#The function that will extract the ProductTypeCategory information from the ProductType column is being defined
def ExtractProductTypeCategory(ProductType):
    if 'T-Shirt' in ProductType or 'Shirt' in ProductType or 'Sweatshirt' in ProductType or 'Coat' in ProductType:
        return 'Top'
    elif 'Pant' in ProductType or 'Skirt' in ProductType:
        return 'Leg'
    elif 'Dress' in ProductType or 'Pyjamas' in ProductType:
        return 'Full'
    else:
        return 'Other'

In [17]:
#ExtractProductTypeCategory function is being applied for each value in the ProductType column
#and the results are being written to the ProductTypeCategory column
productDetailFrame['ProductTypeCategory'] = productDetailFrame['ProductType'].apply(lambda x : ExtractProductTypeCategory(x))
productDetailFrame

             ProductDetail Maturity  Gender ProductType ProductTypeCategory
0            KADIN T-SHIRT    Adult  Female     T-Shirt                 Top
1           KADIN PANTOLON    Adult  Female        Pant                 Leg
2             KADIN GOMLEK    Adult  Female       Shirt                 Top
3             KADIN ELBISE    Adult  Female       Dress                Full
4   ERKEK PIJAMA / GECELIK    Adult    Male     Pyjamas                Full
5   KADIN PIJAMA / GECELIK    Adult  Female     Pyjamas                Full
6            ERKEK T-SHIRT    Adult    Male     T-Shirt                 Top
7               KADIN ETEK    Adult  Female       Skirt                 Leg
8             COCUK ELBISE    Child  Female       Dress                Full
9              COCUK SWEAT    Child  Unisex  Sweatshirt                 Top
10         KIZ COCUK SWEAT    Child  Female  Sweatshirt                 Top
11           BEBEK T-SHIRT     Baby  Unisex     T-Shirt                 Top
12           COCUK T-SHIRT    Child  Unisex     T-Shirt                 Top
13      KIZ COCUK PANTOLON    Child  Female        Pant                 Leg
14          COCUK PANTOLON    Child  Unisex        Pant                 Leg
15        KIZ COCUK ELBISE    Child  Female       Dress                Full
16          KIZ COCUK ETEK    Child  Female       Skirt                 Leg
17       KIZ COCUK T-SHIRT    Child  Female     T-Shirt                 Top
18          BEBEK PANTOLON     Baby  Unisex        Pant                 Leg
19  COCUK PIJAMA / GECELIK    Child  Unisex     Pyjamas                Full
20             ERKEK SWEAT    Adult    Male  Sweatshirt                 Top
21             ERKEK CEKET    Adult    Male        Coat                 Top
22           BAYAN T-SHIRT    Adult  Female     T-Shirt                 Top
23             BAYAN SWEAT    Adult  Female  Sweatshirt                 Top

In [18]:
#Since all information about ProductDetails is kept in the productDetailFrame,
#it will bi sufficient to keep foreign key values of ProductDetails representing the productDetailFrame data in the dataFrame

#dataFrame ProductDetail column is being recreated as productDetailFrame indexes
dataFrame['ProductDetail'] = dataFrame['ProductDetail'].apply(
    lambda x : productDetailFrame.index[productDetailFrame['ProductDetail'] == x].tolist()[0])
dataFrame.head()

,ColorID,ProductDetail,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,...,Quantity,Repair,Delivery,PrintError,SewingError,FabricStain,FabricError,EmbroideryError,MeasureError,SecondQuality
0,18,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,...,405,20,399,4,0,1,1,0,0,6
1,19,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,22,411,0,2,1,0,0,0,3
2,6,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,389,19,378,1,5,2,1,1,1,11
3,20,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,18,406,0,4,2,2,0,0,8
4,2,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,16,411,0,3,0,0,0,0,3

In [19]:
#ProductDetail column is being renamed as ProductDetailID
dataFrame.rename(columns = {'ProductDetail' : 'ProductDetailID'}, inplace = True)
dataFrame.head()

,ColorID,ProductDetailID,FabricCode,FabricDetail,IsManualProcess,Weight,Width,ProductPart,NotchLayer,NotchQuantity,...,Quantity,Repair,Delivery,PrintError,SewingError,FabricStain,FabricError,EmbroideryError,MeasureError,SecondQuality
0,18,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,35,3,...,405,20,399,4,0,1,1,0,0,6
1,19,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,22,411,0,2,1,0,0,0,3
2,6,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,389,19,378,1,5,2,1,1,1,11
3,20,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,18,406,0,4,2,2,0,0,8
4,2,0,2SP050,NE 50/1 PNY 20DE - SUPREM A.EN 32 28 125 G/M2 ...,False,125,150,4,65,3,...,414,16,411,0,3,0,0,0,0,3

In [20]:
#Information of dataframe is being printed
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 206 entries, 0 to 208
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ColorID          206 non-null    int64
 1   ProductDetailID  206 non-null    int64
 2   FabricCode       206 non-null    object
 3   FabricDetail     206 non-null    object
 4   IsManualProcess  206 non-null    bool
 5   Weight           206 non-null    int64
 6   Width            206 non-null    int64
 7   ProductPart      206 non-null    int64
 8   NotchLayer       206 non-null    int64
 9   NotchQuantity    206 non-null    int64
 10  OrderQuantity    206 non-null    int64
 11  Quantity         206 non-null    int64
 12  Repair           206 non-null    int64
 13  Delivery         206 non-null    int64
 14  PrintError       206 non-null    int64
 15  SewingError      206 non-null    int64
 16  FabricStain      206 non-null    int64
 17  FabricError      206 non-null    int64
 18  EmbroideryError  206 non-null    int64
 19  MeasureError     206 non-null    int64
 20  SecondQuality    206 non-null    int64
dtypes: bool(1), int64(18), object(2)
memory usage: 34.0+ KB

In [21]:
#Statistical information of dataframe is being printed
dataFrame.describe()

,ColorID,ProductDetailID,Weight,Width,ProductPart,NotchLayer,NotchQuantity,OrderQuantity,Quantity,Repair,Delivery,PrintError,SewingError,FabricStain,FabricError,EmbroideryError,MeasureError,SecondQuality
count,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000
mean,16.796117,6.330097,171.601942,161.451456,4.902913,64.621359,2.864078,528.956311,574.305825,8.179612,559.199029,4.917476,6.786408,0.635922,2.145631,0.228155,0.393204,15.106796
std,11.881413,7.039801,45.318459,16.988808,2.433564,73.558421,1.571382,812.807992,891.308093,8.979205,866.214970,18.322796,9.375266,2.653754,4.737824,1.246021,1.330964,30.253696
min,0.000000,0.000000,125.000000,120.000000,2.000000,0.000000,0.000000,150.000000,148.000000,0.000000,134.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,5.000000,0.000000,125.000000,150.000000,4.000000,33.000000,2.000000,210.000000,225.750000,3.000000,220.250000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,4.000000
50%,16.000000,3.000000,175.000000,165.000000,4.000000,44.000000,3.000000,275.000000,289.000000,6.000000,284.500000,0.000000,4.000000,0.000000,1.000000,0.000000,0.000000,7.500000
75%,26.000000,12.000000,190.000000,172.000000,5.000000,66.750000,3.000000,400.000000,443.500000,9.000000,437.750000,2.000000,9.000000,0.000000,2.000000,0.000000,0.000000,12.750000
max,47.000000,23.000000,320.000000,195.000000,14.000000,610.000000,14.000000,6000.000000,6605.000000,78.000000,6469.000000,201.000000,88.000000,29.000000,45.000000,15.000000,10.000000,311.000000

In [22]:
#Information of productDetailFrame is being printed
productDetailFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ProductDetail        24 non-null     object
 1   Maturity             24 non-null     object
 2   Gender               24 non-null     object
 3   ProductType          24 non-null     object
 4   ProductTypeCategory  24 non-null     object
dtypes: object(5)
memory usage: 1.1+ KB

In [23]:
#Statistical information of productDetailFrame is being printed
productDetailFrame.describe()

        ProductDetail Maturity  Gender ProductType ProductTypeCategory
count              24       24      24          24                  24
unique             24        3       3           8                   3
top     KADIN T-SHIRT    Adult  Female     T-Shirt                 Top
freq                1       12      14           6                  12

In [24]:
#dataFrame and relational productDetailFrame are being saved as pkl files
dataFrame.to_pickle("../Data/WithRelationalTables/FabricWasteProductDetail.pkl")
productDetailFrame.to_pickle("../Data/WithRelationalTables/ProductDetail.pkl")